// <auto-generated />
using System;
using DenzelDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenzelDev.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260523062624_InitialPortfolioCreate")]
    partial class InitialPortfolioCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenzelDev.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=800&auto=format&fit=crop",
                            ContentMarkdown = "# Mastering Serverless .NET\n\nWhile Vercel is highly optimized for frontend frameworks and serverless Node.js, we can host complete ASP.NET Core architectures using serverless wrapper runtimes like `vercel-dotnet` or serverless functions proxy gateways.\n\n### In this article we cover:\n1. Setting up your `vercel.json` configurations.\n2. Overcoming cold startup times.\n3. Managing connection pool lifetimes inside stateless serverless blocks.\n4. Configuring environment variable secrets safely.",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadTimeMinutes = 6,
                            Slug = "architecting-aspnet-core-serverless-vercel",
                            Title = "Architecting ASP.NET Core for Serverless Deployment on Vercel"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop",
                            ContentMarkdown = "# Styling Premium Web Shaders\n\nGlassmorphism creates unmatched depth on modern dark-mode interfaces. By leveraging modern backdrop filter effects in combination with thin translucent borders, we can make our cards feel floating and premium.\n\n```css\n.glass-card {\n  background: rgba(18, 24, 36, 0.6);\n  backdrop-filter: blur(12px);\n  border: 1px solid rgba(255, 255, 255, 0.08);\n}\n```\n\nThis article outlines exact steps to layer glassmorphic effects on top of standard Bootstrap columns without breaking flexbox flows.",
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadTimeMinutes = 4,
                            Slug = "designing-frost-glass-shaders-tailwind-bootstrap",
                            Title = "Designing Frost-Glass Shaders with Raw Tailwind and Bootstrap 5"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("DenzelDev.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullDescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Full-Stack",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullDescriptionMarkdown = "# EventList Management System\n\nThis application utilizes a stateless, strict **Model-View-Presenter (MVP)** structural design pattern with native ADO.NET and Tailwind CSS.\n\n### Key Features\n- Dynamic budget sheet registers.\n- Timeline coordination sheets.\n- Task allocation matrices.\n- Heavy-weight performance optimization.",
                            GithubUrl = "https://github.com/Denz14-RDI/Hackathon.git",
                            ImageUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=600&auto=format&fit=crop",
                            LiveUrl = "https://eventlist-demo.vercel.app",
                            ShortDescription = "An enterprise-grade, web-based planning platform tailored for student councils, academic organizations, and campus clubs.",
                            Slug = "eventlist-planning-system",
                            Tags = "C#,MVP,ADO.NET,SQL Server,Tailwind",
                            Title = "EventList Planning System"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Full-Stack",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullDescriptionMarkdown = "# Premium Portfolio System\n\nDesigned for maximum elegance, using a custom dark mode palette with cyber-mint accents and micro-animations.\n\n### Highlights\n- Custom **glassmorphism** card shaders.\n- Responsive career timeline nodes.\n- Complete CMS back-office CRUD for blogs and projects.\n- SEO-optimized slug matching.",
                            GithubUrl = "https://github.com/Denz14-RDI/Hackathon.git",
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
                            LiveUrl = "https://denzeldev-portfolio.vercel.app",
                            ShortDescription = "A highly performance-optimized, glassmorphic portfolio styled over Bootstrap 5 and backed by ASP.NET Core MVC and SQL Server.",
                            Slug = "minimalist-developer-portfolio",
                            Tags = "C#,ASP.NET Core,EF Core,SQL Server,Bootstrap 5",
                            Title = "Minimalist Developer Portfolio"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProficiencyPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Languages",
                            IconClass = "bi bi-filetype-cs",
                            Name = "C# / .NET",
                            ProficiencyPercent = 92
                        },
                        new
                        {
                            Id = 2,
                            Category = "Languages",
                            IconClass = "bi bi-database",
                            Name = "SQL / T-SQL",
                            ProficiencyPercent = 88
                        },
                        new
                        {
                            Id = 3,
                            Category = "Languages",
                            IconClass = "bi bi-filetype-js",
                            Name = "TypeScript / JS",
                            ProficiencyPercent = 85
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frameworks",
                            IconClass = "bi bi-bootstrap",
                            Name = "ASP.NET Core MVC",
                            ProficiencyPercent = 90
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frameworks",
                            IconClass = "bi bi-diagram-3",
                            Name = "EF Core ORM",
                            ProficiencyPercent = 88
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frameworks",
                            IconClass = "bi bi-bootstrap-reboot",
                            Name = "Bootstrap 5",
                            ProficiencyPercent = 95
                        },
                        new
                        {
                            Id = 7,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-database-fill",
                            Name = "SQL Server",
                            ProficiencyPercent = 85
                        },
                        new
                        {
                            Id = 8,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-box-seam",
                            Name = "Docker Containers",
                            ProficiencyPercent = 80
                        },
                        new
                        {
                            Id = 9,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-cloud-check",
                            Name = "Vercel / Azure",
                            ProficiencyPercent = 82
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
