// <auto-generated />
using System;
using EventManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManagementSystem.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260609111442_InitialEventListCreate")]
    partial class InitialEventListCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventManagementSystem.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000.00m,
                            EventId = 1,
                            ItemName = "Corporate Sponsorships",
                            Type = "Sponsorship"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600.00m,
                            EventId = 1,
                            ItemName = "Cloud Servers Provisioning",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800.00m,
                            EventId = 1,
                            ItemName = "Physical Promos & Catering",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3500.00m,
                            EventId = 2,
                            ItemName = "University Grant Funding",
                            Type = "Sponsorship"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1200.00m,
                            EventId = 2,
                            ItemName = "Sensor Kits and Arduino Boards",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 800.00m,
                            EventId = 2,
                            ItemName = "Keynote Speaker Honorarium",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1500.00m,
                            EventId = 3,
                            ItemName = "SAEC Budget Allocation",
                            Type = "Sponsorship"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 350.00m,
                            EventId = 3,
                            ItemName = "Seminar Notebooks & Badges",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("EventManagementSystem.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A premier 48-hour programming league challenge designed to assemble software engineering student teams to build dynamic C# applications.",
                            EventDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Manila Tech Dome Complex",
                            OrganizerName = "Student Alliance Executive Council",
                            Title = "National Developer Hackathon 2026"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Annual convention showcasing student robotics research, machine learning modules, and expert-led neural network workshops.",
                            EventDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Quezon Science Hall",
                            OrganizerName = "Robotics & AI Student Chapter",
                            Title = "AI & Robotics Tech Summit"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Leadership training conference focused on budget allocations, project delegation, and campus organization lifecycle management.",
                            EventDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Campus Audio Visual Room",
                            OrganizerName = "Office of Student Affairs",
                            Title = "Student Council Leadership Seminar"
                        });
                });

            modelBuilder.Entity("EventManagementSystem.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Denzel Dev",
                            DueDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "Completed",
                            TaskName = "Provision deployment proxy bridges"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Pres. Alex",
                            DueDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "In Progress",
                            TaskName = "Coordinate judges panel"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Graphics Team",
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "Pending",
                            TaskName = "Distribute promotional details"
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Engr. Clara",
                            DueDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 2,
                            Status = "Completed",
                            TaskName = "Purchase sensor microchips"
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "Dr. Santos",
                            DueDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 2,
                            Status = "Pending",
                            TaskName = "Finalize keynote presentation"
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "Sec. Mark",
                            DueDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 3,
                            Status = "In Progress",
                            TaskName = "Print leadership certificates"
                        });
                });

            modelBuilder.Entity("EventManagementSystem.Models.Budget", b =>
                {
                    b.HasOne("EventManagementSystem.Models.Event", "Event")
                        .WithMany("Budgets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManagementSystem.Models.TaskItem", b =>
                {
                    b.HasOne("EventManagementSystem.Models.Event", "Event")
                        .WithMany("TaskItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManagementSystem.Models.Event", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}

