// <auto-generated />
using System;
using DenzelDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenzelDev.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenzelDev.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=800&auto=format&fit=crop",
                            ContentMarkdown = "# Mastering Serverless .NET\n\nWhile Vercel is highly optimized for frontend frameworks and serverless Node.js, we can host complete ASP.NET Core architectures using serverless wrapper runtimes like `vercel-dotnet` or serverless functions proxy gateways.\n\n### In this article we cover:\n1. Setting up your `vercel.json` configurations.\n2. Overcoming cold startup times.\n3. Managing connection pool lifetimes inside stateless serverless blocks.\n4. Configuring environment variable secrets safely.",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadTimeMinutes = 6,
                            Slug = "architecting-aspnet-core-serverless-vercel",
                            Title = "Architecting ASP.NET Core for Serverless Deployment on Vercel"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop",
                            ContentMarkdown = "# Styling Premium Web Shaders\n\nGlassmorphism creates unmatched depth on modern dark-mode interfaces. By leveraging modern backdrop filter effects in combination with thin translucent borders, we can make our cards feel floating and premium.\n\n```css\n.glass-card {\n  background: rgba(18, 24, 36, 0.6);\n  backdrop-filter: blur(12px);\n  border: 1px solid rgba(255, 255, 255, 0.08);\n}\n```\n\nThis article outlines exact steps to layer glassmorphic effects on top of standard Bootstrap columns without breaking flexbox flows.",
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadTimeMinutes = 4,
                            Slug = "designing-frost-glass-shaders-tailwind-bootstrap",
                            Title = "Designing Frost-Glass Shaders with Raw Tailwind and Bootstrap 5"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000.00m,
                            EventId = 1,
                            ItemName = "Corporate Sponsorships",
                            Type = "Sponsorship"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600.00m,
                            EventId = 1,
                            ItemName = "Cloud Servers Provisioning",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800.00m,
                            EventId = 1,
                            ItemName = "Physical Promos & Catering",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("DenzelDev.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A premier 48-hour programming league challenge designed to assemble software engineering student teams to build dynamic C# applications.",
                            EventDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Manila Tech Dome Complex",
                            OrganizerName = "Student Alliance Executive Council",
                            Title = "National Developer Hackathon 2026"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullDescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Full-Stack",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullDescriptionMarkdown = "# EventList Management System\n\nThis application utilizes a stateless, strict **Model-View-Presenter (MVP)** structural design pattern with native ADO.NET and Tailwind CSS.\n\n### Key Features\n- Dynamic budget sheet registers.\n- Timeline coordination sheets.\n- Task allocation matrices.\n- Heavy-weight performance optimization.",
                            GithubUrl = "https://github.com/Denz14-RDI/Hackathon.git",
                            ImageUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=600&auto=format&fit=crop",
                            LiveUrl = "https://eventlist-demo.vercel.app",
                            ShortDescription = "An enterprise-grade, web-based planning platform tailored for student councils, academic organizations, and campus clubs.",
                            Slug = "eventlist-planning-system",
                            Tags = "C#,MVP,ADO.NET,SQL Server,Tailwind",
                            Title = "EventList Planning System"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Full-Stack",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullDescriptionMarkdown = "# Premium Portfolio System\n\nDesigned for maximum elegance, using a custom dark mode palette with cyber-mint accents and micro-animations.\n\n### Highlights\n- Custom **glassmorphism** card shaders.\n- Responsive career timeline nodes.\n- Complete CMS back-office CRUD for blogs and projects.\n- SEO-optimized slug matching.",
                            GithubUrl = "https://github.com/Denz14-RDI/Hackathon.git",
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
                            LiveUrl = "https://denzeldev-portfolio.vercel.app",
                            ShortDescription = "A highly performance-optimized, glassmorphic portfolio styled over Bootstrap 5 and backed by ASP.NET Core MVC and SQL Server.",
                            Slug = "minimalist-developer-portfolio",
                            Tags = "C#,ASP.NET Core,EF Core,SQL Server,Bootstrap 5",
                            Title = "Minimalist Developer Portfolio"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProficiencyPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Languages",
                            IconClass = "bi bi-filetype-cs",
                            Name = "C# / .NET",
                            ProficiencyPercent = 92
                        },
                        new
                        {
                            Id = 2,
                            Category = "Languages",
                            IconClass = "bi bi-database",
                            Name = "SQL / T-SQL",
                            ProficiencyPercent = 88
                        },
                        new
                        {
                            Id = 3,
                            Category = "Languages",
                            IconClass = "bi bi-filetype-js",
                            Name = "TypeScript / JS",
                            ProficiencyPercent = 85
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frameworks",
                            IconClass = "bi bi-bootstrap",
                            Name = "ASP.NET Core MVC",
                            ProficiencyPercent = 90
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frameworks",
                            IconClass = "bi bi-diagram-3",
                            Name = "EF Core ORM",
                            ProficiencyPercent = 88
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frameworks",
                            IconClass = "bi bi-bootstrap-reboot",
                            Name = "Bootstrap 5",
                            ProficiencyPercent = 95
                        },
                        new
                        {
                            Id = 7,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-database-fill",
                            Name = "SQL Server",
                            ProficiencyPercent = 85
                        },
                        new
                        {
                            Id = 8,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-box-seam",
                            Name = "Docker Containers",
                            ProficiencyPercent = 80
                        },
                        new
                        {
                            Id = 9,
                            Category = "Databases & Devops",
                            IconClass = "bi bi-cloud-check",
                            Name = "Vercel / Azure",
                            ProficiencyPercent = 82
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Denzel Dev",
                            DueDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "Completed",
                            TaskName = "Provision deployment proxy bridges"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Pres. Alex",
                            DueDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "In Progress",
                            TaskName = "Coordinate judges panel"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Graphics Team",
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            Status = "Pending",
                            TaskName = "Distribute promotional details"
                        });
                });

            modelBuilder.Entity("DenzelDev.Models.Budget", b =>
                {
                    b.HasOne("DenzelDev.Models.Event", "Event")
                        .WithMany("Budgets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DenzelDev.Models.TaskItem", b =>
                {
                    b.HasOne("DenzelDev.Models.Event", "Event")
                        .WithMany("TaskItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DenzelDev.Models.Event", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
